### ISSUE TITLE
Performance replication for WGAN

### ISSUE THREAD

**Issue by prclibo** [w86763777/pytorch-gan-collections#10]
Hello, thanks for creating this repo and I found it very helpful for me to play with basic GAN structures. I tried to replicate the reported performance by running the code with the following setups

```
python wgan.py
python wgan.py --arch=cnn32 --logdir=./logs/WGAN_CIFAR10_CNN32/
python wgangp.py
```

I got FID plot as follows. The FID of WGAN on CIFAR10 is ~80, which is much larger than the reported 33.27. The FID on WGAN(RES) is even worse. I was wondering how I could replicate the 33 FID. Also I am pretty confused how ResNet is performing worse than CNN. It'd be helpful if you can give any hints. Thanks!

![image](https://user-images.githubusercontent.com/1730013/148484954-6cd5749f-f62a-4d7b-9302-fe957724906b.png)

**Comment by w86763777** [comment]
Thanks for your reports.

There are some incorrect default parameters in `wgan.py`. If you want to train  WGAN with DCGAN model, you should use
```
python wgan.py --flagfile ./config/WGAN_CIFAR10_CNN.txt
```
which will load the correct parameter for DCGAN. I will fix this bug as soon as possible.

I didn't test the ResNet model with WGAN since this model is proposed after the WGAN. That is why the default parameters of `wgan.py` is incorrect and confused you.

**Comment by w86763777** [comment]
I have updated the default parameters of `wgan.py`. If you follow the [reproducing step](https://github.com/w86763777/pytorch-gan-collections#reproduce) and still get the inconsistent results, you can open the issue again.

Thanks
